Herramienta/cursos/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from Herramienta.models import Curso


class CrearUsuarioForm(FlaskForm):
    nombre = StringField("Nombre", validators=[
                        DataRequired(), Length(min=1, max=70)])
    submit = SubmitField("Crear curso")

    def validate_nombre(self, nombre):
        user = Curso.query.filter_by(nombre=nombre.data).first()
        if user:
            raise ValidationError("Curso ya existente")

class EditarNombreCursoForm(FlaskForm):
    nombre = StringField("Nombre", validators=[
                        DataRequired(), Length(min=1, max=70)])
    submit = SubmitField("Cambiar nombre curso")

    def validate_nombre(self, nombre):
        user = Curso.query.filter_by(nombre=nombre.data).first()
        if user:
            raise ValidationError("Curso ya existente")

class AgregarSemestreACursoForm(FlaskForm) :
    semestre = SelectField("Semestre a añadir", choices=[], coerce=int)
    submit = SubmitField("Agregar semestre a curso") 

class EliminarSemestreACursoForm(FlaskForm) :
    submit = SubmitField("Eliminar semestre") 

class EliminarCursoForm(FlaskForm) :
    submit = SubmitField("Eliminar curso") 

Herramienta/cursos/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
from flask_login import current_user, login_required
from Herramienta.models import Usuario, Curso, Semestre, Actividad, Grupo, SemestreCursoHabilitados, ListaUsuariosSemestreCurso, Calificacion
from Herramienta import db, bcrypt
from Herramienta.cursos.forms import CrearUsuarioForm, EditarNombreCursoForm, AgregarSemestreACursoForm, EliminarSemestreACursoForm, EliminarCursoForm

cursos = Blueprint("cursos", __name__)

@cursos.route("/cursos")
@login_required
def get_cursos():
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    listaCursos = ListaUsuariosSemestreCurso.query.filter_by(usuario_id=user_id).all()
    posiblesCursos = Curso.query.all()
    cursos = []
    if user.rol_id == 1:
        for curso in posiblesCursos:
            for cursoEnLista in listaCursos:
                if cursoEnLista.curso_id == curso.id:
                    cursos.append(curso)
    else:
        cursos = posiblesCursos
    return render_template("cursos/cursos.html", title="Cursos", cursos=cursos)

@cursos.route("/crear_curso", methods=["GET", "POST"])
@login_required
def crear_curso():
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    form = CrearUsuarioForm()
    if form.validate_on_submit():
        semestres=[]
        curso = Curso(nombre=form.nombre.data,
                       semestres=semestres)
        db.session.add(curso)
        db.session.commit()
        flash(f"Curso creado exitosamente", "success")
        return redirect(url_for("cursos.get_cursos"))
    return render_template("cursos/crear_curso.html", title="Crear curso", form=form)

@cursos.route("/cursos/<int:curso_id>/editar", methods=["GET", "POST"])
@login_required
def editar_curso(curso_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    curso = Curso.query.get_or_404(curso_id)
    form = EditarNombreCursoForm()
    if form.validate_on_submit():
        curso.nombre = form.nombre.data
        db.session.commit()
        flash(f"Curso actualizado exitosamente", "success")
        return redirect(url_for("cursos.get_cursos"))
    elif request.method == "GET":
        form.nombre.data = curso.nombre
    return render_template("cursos/editar_curso.html", title="Editar curso", form=form)

@cursos.route("/cursos/<int:curso_id>", methods=["GET", "POST"])
@login_required
def ver_curso(curso_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        habilitado = ListaUsuariosSemestreCurso.query.filter_by(usuario_id=user_id, curso_id=curso_id).first()
        if not habilitado:
            abort(403)
    curso = Curso.query.get_or_404(curso_id)
    listaSemestres = SemestreCursoHabilitados.query.filter_by(curso_id=curso_id).all()
    semestres = []
    numActividadesHabilitadasTotal = 0
    for s in listaSemestres:
        numActividadesHabilitadas = 0
        semestre = Semestre.query.get_or_404(s.semestre_id)
        listaActividades = Actividad.query.filter_by(semestre_id=s.semestre_id, curso_id=curso_id).all()
        for actividad in listaActividades:
            if actividad.habilitada:
                numActividadesHabilitadas = numActividadesHabilitadas + 1
                numActividadesHabilitadasTotal = numActividadesHabilitadasTotal +1
        listaUsuarios=ListaUsuariosSemestreCurso.query.filter_by(semestre_id=s.semestre_id, curso_id=curso_id).all()
        anadir = False
        if user.rol_id == 1:
            usuarioEnLista = ListaUsuariosSemestreCurso.query.filter_by(semestre_id=s.semestre_id, curso_id=curso_id, usuario_id=user_id).first()
            if usuarioEnLista is not None:
                anadir = True
        else:
            anadir = True
        if anadir:
            numUsuarios = len(listaUsuarios)
            semestreAnadir = {
                "id": semestre.id,
                "nombre" : semestre.nombre,
                "estudiantes" : semestre.estudiantes,
                "usuarios": numUsuarios,
                "actividades" : semestre.actividades,
                "habilitado" : s.habilitado,
                "actividadesHabilitadas" : numActividadesHabilitadas
            }
            semestres.append(semestreAnadir)
    return render_template("cursos/ver_curso.html", title="Ver curso", curso=curso, semestres=semestres, numActividadesHabilitadasTotal=numActividadesHabilitadasTotal)

@cursos.route("/cursos/<int:curso_id>/<int:semestre_id>/cambiarEstado", methods=["GET", "POST"])
@login_required
def cambiarEstadoSemestreCurso(curso_id,semestre_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    elemento = SemestreCursoHabilitados.query.filter_by(semestre_id=semestre_id, curso_id=curso_id).first()
    elemento.habilitado = not elemento.habilitado
    db.session.commit()
    return redirect(url_for("cursos.ver_curso", curso_id=curso_id))

@cursos.route("/cursos/<int:curso_id>/editarNombre", methods=["GET", "POST"])
@login_required
def editarNombre_curso(curso_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    curso = Curso.query.get_or_404(curso_id)
    form = EditarNombreCursoForm()
    if form.validate_on_submit():
        curso.nombre = form.nombre.data
        db.session.commit()
        flash(f"Curso actualizado exitosamente", "success")
        return redirect(url_for("cursos.ver_curso", curso_id=curso.id))
    elif request.method == "GET":
        form.nombre.data = curso.nombre
    return render_template("cursos/editar_nombre_curso.html", title="Cambiar nombre curso", form=form, curso=curso)

@cursos.route("/cursos/<int:curso_id>/agregarSemestre", methods=["GET", "POST"])
@login_required
def agregarSemestre_curso(curso_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    curso = Curso.query.get_or_404(curso_id)
    semestresActuales = curso.semestres
    semestres = [(s.id, s.nombre)
              for s in Semestre.query.all() if s not in semestresActuales]
    form = AgregarSemestreACursoForm(request.form)
    form.semestre.choices = semestres
    if form.validate_on_submit():
        semestreAnadir = Semestre.query.filter_by(id=form.semestre.data).first()
        curso.semestres.append(semestreAnadir)
        semestreCurso = SemestreCursoHabilitados(semestre_id=semestreAnadir.id,curso_id=curso_id,habilitado=True)
        db.session.add(semestreCurso)
        db.session.commit()
        flash(f"Semestre añadido exitosamente", "success")
        return redirect(url_for("cursos.ver_curso", curso_id=curso.id))
    return render_template("cursos/anadirSemestre_curso.html", title="Anadir semestre a curso", form=form, curso=curso, semestres=semestres)


@cursos.route("/cursos/<int:curso_id>/eliminarSemestre/<int:semestre_id>", methods=["GET", "POST"])
@login_required
def eliminarCurso_semestre(semestre_id, curso_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    semestre = Semestre.query.get_or_404(semestre_id)
    curso = Curso.query.get_or_404(curso_id)
    form = EliminarSemestreACursoForm()
    if form.validate_on_submit():
        curso.semestres.remove(semestre)
        semestreCurso = SemestreCursoHabilitados.query.filter_by(semestre_id=semestre_id, curso_id=curso_id).first()
        db.session.delete(semestreCurso)
        db.session.commit()
        flash(f"Semestre eliminado exitosamente", "success")
        return redirect(url_for("cursos.ver_curso", curso_id=curso.id))
    return render_template("cursos/eliminarSemestre_curso.html", title="Eliminar semestre a curso", form=form, semestre=semestre, curso=curso)


@cursos.route("/cursos/<int:curso_id>/eliminarCurso", methods=["GET", "POST"])
@login_required
def eliminar_curso(curso_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    curso = Curso.query.get_or_404(curso_id)
    actividades = Actividad.query.filter_by(curso_id=curso.id).all()
    form = EliminarCursoForm()
    if form.validate_on_submit():
        for actividad in actividades:
            grupos = Grupo.query.filter_by(actividad_id=actividad.id).all()
            for grupo in grupos:
                listaCalificaciones = Calificacion.query.filter_by(grupo_id=grupo.id).all()
                for calificacion in listaCalificaciones:
                    db.session.delete(calificacion)
                    db.session.commit()
                db.session.delete(grupo)
                db.session.commit()
            eliminarActividad(actividad.id)
            db.session.commit()
        for semestre in curso.semestres:
            curso.semestres.remove(semestre)

Herramienta/templates/cursos/anadirSemestre_curso.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('cursos.ver_curso', curso_id=curso.id) }}">
                    <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            {% if not semestres %}
                <br>
                <h4>No hay semestres para añadir a este curso.</h4>
            {% else %}
                <div class="content-section">
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Añadir semestre a curso</legend>
                            <div class="form-group">
                                {{ form.semestre.label(class="form-control-label") }}
                                {% if form.semestre.errors %}
                                {{ form.crm.semestre(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedbakc">
                                    {% for error in form.semestre.errors%}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                <br>
                                {{ form.semestre(size=1, maxlength=50,class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                        </fieldset>
                        <div class="form-group">
                            {{ form.submit(class="btn btn-outline-info")}}
                        </div>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

Herramienta/templates/cursos/crear_curso.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('cursos.get_cursos')}}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Crear curso</legend>
                        <div class="form-group">
                            {{ form.nombre.label(class="form-control-label") }}

                            {% if form.nombre.errors %}
                                {{ form.nombre(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedbakc">
                                    {% for error in form.nombre.errors%}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.nombre(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/cursos/cursos.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        {% if current_user.rol_id == 2 or current_user.rol_id == 3 or current_user.rol_id == 4%}
            <div class="col-md-7">
        {% else %}
            <div class="col-md-10">
        {% endif %}
        <h1>Lista de cursos</h1>
        {% if cursos %}
            {% for curso in cursos %}
                <article class="media content-section">
                    <div class="media-body">
                        <div class="article-metadata">
                            <h2><a class="mr-2">{{ curso.nombre }}</a></h2>
                        </div>
                            <form action="{{ url_for('cursos.ver_curso', curso_id=curso.id) }}">
                                    <button type="submit" class="btn btn-outline-info verButton">Ver curso</button>
                            </form>
                    </div>
                </article>
            {% endfor %}
        {% else %}
            <h4>No hay cursos</h4>
        {% endif %}
            </div>
            <div class="col-md-5">
                {% if current_user.rol_id == 2 or current_user.rol_id == 3 or current_user.rol_id == 4%}
                <div class="content-section">
                    <h3>Acciones cursos</h3>
                    <div>
                        <form action="{{ url_for('cursos.crear_curso') }}">
                            <button type="submit" class="btn btn-outline-info cursosActionsButton">Crear curso</button>
                        </form>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/cursos/editar_curso.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Crear curso</legend>
                        <div class="form-group">
                            {{ form.nombre.label(class="form-control-label") }}

                            {% if form.nombre.errors %}
                            {{ form.nombre(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedbakc">
                                {% for error in form.nombre.errors%}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.nombre(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/cursos/editar_nombre_curso.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('cursos.ver_curso', curso_id=curso.id) }}">
                    <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Cambiar nombre curso</legend>
                        <div class="form-group">
                            {{ form.nombre.label(class="form-control-label") }}

                            {% if form.nombre.errors %}
                            {{ form.nombre(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedbakc">
                                {% for error in form.nombre.errors%}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.nombre(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/cursos/eliminarSemestre_curso.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('cursos.ver_curso', curso_id=curso.id) }}">
                    <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
                <div class="content-section">
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Eliminar curso a semestre</legend>
                            <h5>¿Desea eliminar el semestre {{ semestre.nombre }} del curso {{ curso.nombre}}?</h5>
                        </fieldset>
                        <div class="form-group">
                            {{ form.submit(class="btn btn-outline-info")}}
                        </div>
                    </form>
                </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/cursos/ver_curso.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <form action="{{ url_for('cursos.get_cursos')}}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <br>
            <article class="media content-section">
                <div class="media-body">
                    <div class="article-metadata">
                        <h3 class="mr-2">{{ curso.nombre }}</h3>
                    </div>
                    {% if current_user.rol_id != 1 %}
                        <form action="{{ url_for('cursos.editarNombre_curso', curso_id=curso.id) }}">
                            <button type="submit" class="btn btn-outline-info semestreActions">Cambiar nombre curso</button>
                        </form>
                        <form action="{{ url_for('cursos.eliminar_curso', curso_id=curso.id) }}">
                            <button type="submit" class="btn btn-outline-danger semestreActions">Eliminar curso</button>
                        </form>
                        <form action="{{ url_for('cursos.agregarSemestre_curso', curso_id=curso.id) }}">
                            <button type="submit" class="btn btn-outline-info semestreActions">Agregar semestre a curso</button>
                        </form>
                    {% endif %}
                    {% if not semestres %}
                        <h4>No hay semestres asignados a este curso</h4>
                    {% else %}
                            {% if current_user.rol_id != 1 %}
                                <table id="listaEstudiantes" class="hover" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>Periodo</th>
                                            <th>Núm. Estudiantes</th>
                                            <th>Núm. Monitores</th>
                                            <th>Núm. Actividades</th>
                                            <th>Ver actividades</th>                                            
                                            <th>Ver Estudiantes</th>
                                            <th>Ver Monitores</th>
                                            <th><img class="habilitarButton" src="/static/icons/tick.png" alt="check image"></th>
                                            <th><img class="habilitarButton" src="/static/icons/x.png" alt="check image"></th>
                                            <th><img class="habilitarButton" src="/static/icons/trash.png" alt="check image"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for semestre in semestres %}
                                        <tr>
                                            <td>{{ semestre.nombre }}</td>
                                            <td>{{ semestre.estudiantes|length }}</td>
                                            <td>{{ semestre.usuarios }}</td>
                                            <td>{{ semestre.actividades|length }}</td>
                                            <td>
                                                <form action="{{ url_for('actividades.verActividades_semestre', curso_id=curso.id, semestre_id=semestre.id) }}">
                                                    <button type="submit" class="btn btn-outline-info eliminarCursoSemestre">Ver actividades</button>
                                                </form>
                                            </td>
                                            <td>
                                                <form action="{{ url_for('semestres.verLista_semestre', curso_id=curso.id, semestre_id=semestre.id) }}">
                                                    <button type="submit" class="btn btn-outline-info eliminarCursoSemestre">Ver estudiantes</button>
                                                </form>
                                            </td>
                                            <td>
                                                <form action="{{ url_for('usuarios.verMonitores', curso_id=curso.id, semestre_id=semestre.id) }}">
                                                    <button type="submit" class="btn btn-outline-info eliminarCursoSemestre">Ver monitores</button>
                                                </form>
                                            </td>
                                            {% if semestre.habilitado %}
                                                <td>
                                                    <img src="/static/icons/tick-disabled.png" class="habilitarButton" alt="check image">
                                                </td>
                                                <td>
                                                    <form action="{{ url_for('cursos.cambiarEstadoSemestreCurso', semestre_id=semestre.id,  curso_id=curso.id) }}">
                                                        <button type="submit" class="checkButton"><img src="/static/icons/x.png" class="habilitarButton" alt="check image"></button>
                                                    </form>
                                                </td>
                                            {% else %}
                                            <td>
                                                <form action="{{ url_for('cursos.cambiarEstadoSemestreCurso', semestre_id=semestre.id,  curso_id=curso.id) }}">
                                                    <button type="submit" class="checkButton"><img src="/static/icons/tick.png" class="habilitarButton" alt="check image"></button>
                                                </form>
                                            </td>
                                            <td>
                                                <img src="/static/icons/x-disabled.png" class="habilitarButton" alt="check image">
                                            </td>
                                            {% endif %}
                                            <td>
                                                <form action="{{ url_for('cursos.eliminarCurso_semestre', semestre_id=semestre.id,  curso_id=curso.id) }}">
                                                    <button type="submit" class="checkButton"><img src="/static/icons/trash.png" class="habilitarButton" alt="check image"></button>
                                                </form>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>Periodo</th>
                                            <th>Núm. Estudiantes</th>
                                            <th>Núm. Monitores</th>
                                            <th>Núm. Actividades</th>
                                            <th>Ver actividades</th>                                            
                                            <th>Ver Estudiantes</th>
                                            <th>Ver Monitores</th>
                                            <th><img class="habilitarButton" src="/static/icons/tick.png" alt="check image"></th>
                                            <th><img class="habilitarButton" src="/static/icons/x.png" alt="check image"></th>
                                            <th><img class="habilitarButton" src="/static/icons/trash.png" alt="check image"></th>
                                        </tr>
                                    </tfoot>
                                </table>
                            {% elif numActividadesHabilitadasTotal != 0 %}
                                <table id="listaEstudiantes" class="hover" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>Periodo</th>
                                            <th>Núm. Actividades habilitadas</th>
                                            <th>Ver actividades</th>                                            
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for semestre in semestres %}
                                            <tr>
                                                {% if semestre.habilitado %}
                                                    <td>{{ semestre.nombre }}</td>
                                                    <td>{{ semestre.actividadesHabilitadas }}</td>
                                                    <td>
                                                        <form action="{{ url_for('actividades.verActividades_semestre', curso_id=curso.id, semestre_id=semestre.id) }}">
                                                            <button type="submit" class="btn btn-outline-info eliminarCursoSemestre">Ver actividades</button>
                                                        </form>
                                                    </td>
                                                {% endif %}
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>Periodo</th>
                                            <th>Núm. Actividades habilitadas</th>
                                            <th>Ver actividades</th>   
                                        </tr>
                                    </tfoot>
                                </table>
                            {% else %}
                                <h4>No hay actividades habilitadas para calificar</h4>
                            {% endif %}
                    {% endif %}
                </div>
            </article>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('#listaEstudiantes').DataTable({
                "language" : {
                    "url" : "//cdn.datatables.net/plug-ins/1.10.20/i18n/Spanish.json"
                }
            });
        } );
    </script>
{% endblock content %}