Herramienta/usuarios/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from Herramienta.models import Usuario, Rol


class RegistrationForm(FlaskForm):
    login = StringField("Login", validators=[
                        DataRequired(), Length(min=2, max=20)])
    rol = SelectField("Tipo de usuario", choices=[], coerce=int)
    submit = SubmitField("Crear usuario")

class CrearMonitorForm(FlaskForm):
    login = StringField("Login", validators=[
                        DataRequired(), Length(min=2, max=20)])
    submit = SubmitField("Crear monitor")

class LoginForm(FlaskForm):
    login = StringField("Login", validators=[DataRequired()])
    password = PasswordField("Contraseña", validators=[DataRequired()])
    submit = SubmitField("Iniciar sesión")


class RequestResetForm(FlaskForm):
    login = StringField("Login", validators=[DataRequired()])
    submit = SubmitField("Solicitar cambio de contraseña")

class ResetPasswordForm(FlaskForm):
    password = PasswordField("Nueva contraseña", validators=[DataRequired()])
    confirm_password = PasswordField(" Confirmar contraseña", validators=[
                                     DataRequired(), EqualTo("password")])
    submit = SubmitField("Cambiar contraseña")

class EditarNombreUsuarioForm(FlaskForm):
    login = StringField("Usuario", validators=[
                        DataRequired(), Length(min=2, max=20)])
    submit = SubmitField("Editar usuario")

class EditarRolUsuarioForm(FlaskForm):
    rol = SelectField("Tipo de usuario", choices=[], coerce=int)
    submit = SubmitField("Editar usuario")

class AgregarCursoAUsuarioForm(FlaskForm) :
    curso = SelectField("Semestre a añadir", choices=[], coerce=int)
    submit = SubmitField("Agregar curso a usuario") 

class EliminarCursosAUsuarioForm(FlaskForm) :
    submit = SubmitField("Eliminar curso") 

class EliminarUsuarioForm(FlaskForm):
    submit = SubmitField("Eliminar usuario") 

class EliminarMonitorAsignadoForm(FlaskForm):
    submit = SubmitField("Eliminar monitor") 

class EstablecerContraseñaForm(FlaskForm):
    password = PasswordField("Contraseña", validators=[
                             DataRequired(), Length(min=6, max=50)])
    confirm_password = PasswordField(" Confirmar constraseña", validators=[
                                     DataRequired(), EqualTo("password")])
    submit = SubmitField("Establecer contraseña") 

class ActivarUsuarioForm(FlaskForm):
    nombres = StringField("Nombres ", validators=[DataRequired()])
    apellidos = StringField("Apellidos", validators=[DataRequired()])
    submit = SubmitField("Aceptar") 

Herramienta/usuarios/routes.py
import random
import string
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
from flask_login import login_user, current_user, logout_user, login_required
from Herramienta import db, bcrypt
from Herramienta.models import Usuario, Rol, Curso, ListaUsuariosSemestreCurso, Semestre
from Herramienta.usuarios.forms import (RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm,
                                        EditarNombreUsuarioForm, EditarRolUsuarioForm, AgregarCursoAUsuarioForm, EliminarCursosAUsuarioForm,
                                        EliminarUsuarioForm, EstablecerContraseñaForm, ActivarUsuarioForm, EliminarMonitorAsignadoForm, CrearMonitorForm)
from Herramienta.usuarios.utils import send_reset_email,usuario_creado_email

usuarios = Blueprint("usuarios", __name__)


@usuarios.route("/register", methods=["GET", "POST"])
@login_required
def register():
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id != 4:
        abort(403)
    roles = [(r.id, r.nombre) for r in Rol.query.all()]
    form = RegistrationForm(request.form)
    form.rol.choices = roles
    password = randomString(10)
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(password).decode("utf-8")
        user = Usuario(login=form.login.data,
                       password=hashed_password, rol_id=form.rol.data, activado=False)
        db.session.add(user)
        db.session.commit()
        usuario = Usuario.query.filter_by(login=form.login.data).first()
        usuario_creado_email(usuario)
        flash(f"Usuario creado exitosamente. Es necesario que este usuario establezca su propia contraseña.", "success")
        return redirect(url_for("usuarios.get_usuarios"))
    return render_template("usuarios/crear_usuario.html", title="Crear usuario", form=form)

@usuarios.route("/crearMonitor/<int:curso_id>/<int:semestre_id>", methods=["GET", "POST"])
@login_required
def crearMonitor(curso_id,semestre_id):
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    form = CrearMonitorForm()
    password = randomString(10)
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(password).decode("utf-8")
        user = Usuario(login=form.login.data,
                       password=hashed_password, rol_id=1, activado=False)
        db.session.add(user)
        db.session.commit()
        usuario = Usuario.query.filter_by(login=form.login.data).first()
        usuario_creado_email(usuario)
        flash(f"Monitor creado exitosamente. Es necesario que este usuario establezca su propia contraseña.", "success")
        return redirect(url_for("usuarios.verMonitores", curso_id=curso_id, semestre_id=semestre_id))
    return render_template("usuarios/crear_monitor.html", title="Crear monitor", form=form, legend="Monitor")

@usuarios.route("/crearProfesor/<int:curso_id>/<int:semestre_id>", methods=["GET", "POST"])
@login_required
def crearProfesor(curso_id,semestre_id):
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    form = CrearMonitorForm()
    password = randomString(10)
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(password).decode("utf-8")
        user = Usuario(login=form.login.data,
                       password=hashed_password, rol_id=3, activado=False)
        db.session.add(user)
        db.session.commit()
        usuario = Usuario.query.filter_by(login=form.login.data).first()
        usuario_creado_email(usuario)
        flash(f"Profesor creado exitosamente. Es necesario que este usuario establezca su propia contraseña.", "success")
        return redirect(url_for("usuarios.verMonitores", curso_id=curso_id, semestre_id=semestre_id))
    return render_template("usuarios/crear_monitor.html", title="Crear profesor", form=form, legend="Profesor")

@usuarios.route("/crearAsistente/<int:curso_id>/<int:semestre_id>", methods=["GET", "POST"])
@login_required
def crearAsistente(curso_id,semestre_id):
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    form = CrearMonitorForm()
    password = randomString(10)
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(password).decode("utf-8")
        user = Usuario(login=form.login.data,
                       password=hashed_password, rol_id=2, activado=False)
        db.session.add(user)
        db.session.commit()
        usuario = Usuario.query.filter_by(login=form.login.data).first()
        usuario_creado_email(usuario)
        flash(f"Asistente graduado creado exitosamente. Es necesario que este usuario establezca su propia contraseña.", "success")
        return redirect(url_for("usuarios.verMonitores", curso_id=curso_id, semestre_id=semestre_id))
    return render_template("usuarios/crear_monitor.html", title="Crear Asistente graduado", form=form, legend="Asistente graduado ")

@usuarios.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = Usuario.query.filter_by(login=form.login.data).first()
        if user:
            send_reset_email(user)
            flash('Un correo ha sido enviado con las instrucciones para el cambio de la contraseña.', 'info')
            return redirect(url_for('usuarios.login'))
        else:
            flash("El login ingresado no existe en el Opticorrector", "danger")
    return render_template('usuarios/reset_password.html', title='Reset Password', form=form)

@usuarios.route("/resetPassword/<token>", methods=["GET", "POST"])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = Usuario.verify_token_password(token)
    if user is None:
        flash('El link de cambio de contraseña ha expirado. Necesitas crear uno nuevo de la misma manera en que creaste el anterior', 'warning')
        return redirect(url_for('main.home'))
    form = EstablecerContraseñaForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('La constreña ha sido definida. Ya puedes iniciar sesión.', 'success')
        return redirect(url_for('usuarios.login'))
    return render_template('usuarios/establecerContrasena.html', title='Cambiar contraseña', form=form)

@usuarios.route("/resetPassword/<int:usuario_id>", methods=["GET", "POST"])
def cambiar_contrasena(usuario_id):
    user = Usuario.query.get_or_404(usuario_id)
    form = EstablecerContraseñaForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('La constreña ha sido definida', 'success')
        return redirect(url_for('cursos.get_cursos'))
    return render_template('usuarios/establecerContrasena.html', title='Cambiar contraseña', form=form)


@usuarios.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = Usuario.query.filter_by(login=form.login.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Login o contraseña invalidos.", "danger")
    return render_template("usuarios/login.html", title="Iniciar sesión", form=form)


@usuarios.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@usuarios.route("/usuarios", methods=["GET", "POST"])
@login_required
def get_usuarios():
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id != 4:
        abort(403)
    page = request.args.get("page", 1, type=int)
    usuarios = Usuario.query.order_by(
        Usuario.id.desc()).paginate(page=page, per_page=5)
    return render_template("usuarios/usuarios.html", title="Usuarios", usuarios=usuarios, usuario=user)


@usuarios.route("/cuenta", methods=["GET", "POST"])
@login_required
def cuenta():
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    rol = Rol.query.filter_by(id=user.rol_id).first()
    return render_template("usuarios/cuenta.html", title="Mi cuenta", usuario=user, rol=rol)


@usuarios.route("/usuarios/<int:usuario_id>/editarNombre", methods=["GET", "POST"])
@login_required
def editarNombre_usuario(usuario_id):
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id != 4:
        abort(403)
    usuario = Usuario.query.get_or_404(usuario_id)
    form = EditarNombreUsuarioForm()
    if form.validate_on_submit():
        usuario.login = form.login.data
        db.session.commit()
        flash(f"Usuario actualizado exitosamente", "success")
        return redirect(url_for("usuarios.ver_usuario", usuario_id=usuario.id))
    elif request.method == "GET":
        form.login.data = usuario.login
    return render_template("usuarios/editarNombre_usuario.html", title="Editar usuario", form=form)

@usuarios.route("/usuarios/<int:usuario_id>/editarRol", methods=["GET", "POST"])
@login_required
def editarRol_usuario(usuario_id):
    user_id = current_user.get_id()

Herramienta/templates/usuarios/agregarAsistente.html
{% extends "layout.html" %}

{% block content %}
    <p id="cursoId">{{curso.id}}</p>
    <p id="semestreId">{{semestre.id}}</p>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form action="{{ url_for('usuarios.verMonitores', curso_id=curso.id, semestre_id=semestre.id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            {% if not monitoresJSON %}
                <h4>No hay asistentes graduados registrados para poder añadir.</h4>
                <form action="{{ url_for('usuarios.crearAsistente', curso_id=curso.id, semestre_id=semestre.id) }}">
                    <button type="submit" class="btn btn-outline-info usuariossActionsButton">Crear asistente graduado</button>
                </form>
            {% else %}
                <div class="content-section">
                    <form method="POST" action="" enctype="multipart/form-data" id="createForm" name="createForm">
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Añadir asistentes graduados - {{ curso.nombre }} - {{ semestre.nombre}}</legend>
                            <div class="form-group" id="listaEstudiantes">
                                <div class="row">
                                    <div class="col-md-2"></div>
                                    <div class="col-md-2">
                                        <p style="text-align: center;"><strong>Login</strong></p>
                                    </div>
                                    <div class="col-md-3">
                                        <p style="text-align: center;"><strong>Apellidos</strong></p style="text-align: center;">
                                    </div>
                                    <div class="col-md-3">
                                        <p style="text-align: center;"><strong>Nombres</strong></p style="text-align: center;">
                                    </div>
                                </div>
                                <div class="row" id="estudiante">
                                    <div class="col-md-2"></div>
                                    <div class="col-md-2">
                                        <input type="text" class="form-control" name="login" id="login">
                                    </div>
                                    <div class="col-md-3">
                                        <p id="apellidos" class="notFound">Apellidos</p>
                                    </div>
                                    <div class="col-md-3">
                                        <p id="nombres" class="notFound">Nombres</p>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <br>
                        <button class="btn btn-success semestreActions" onclick="verificarMonitorSeleccionado(event)">Agregar monitor</button>
                    </form>
                </div>
            {% endif %}
            <form action="{{ url_for('usuarios.crearAsistente', curso_id=curso.id, semestre_id=semestre.id) }}">
                <button type="submit" class="btn btn-outline-info usuariossActionsButton" id="botonCrearMonitor">Crear monitor</button>
            </form>
            <form
            action="{{ url_for('usuarios.monitorAgregado', curso_id=curso.id, semestre_id=semestre.id,monitorSeleccionado='2') }}" id="formAnadirMonitor">
            <button type="submit" class="btn btn-outline-info semestreActions" id="buttonAnadirMonitor"></button>
        </form>
        </div>
    </div>
    <script>

        let botonCrearMonitor = document.getElementById("botonCrearMonitor");
        botonCrearMonitor.style.display = "none";

        let curso_id = document.getElementById("cursoId");
        curso_id.style.display = "none";

        let semestre_id = document.getElementById("semestreId");
        semestre_id.style.display = "none";

        let buttonAnadirMonitor = document.getElementById("buttonAnadirMonitor");
        buttonAnadirMonitor.style.display = "none";

        let actionFormbuttonAnadirMonitor = document.getElementById("formAnadirMonitor")

        let monitores = JSON.parse('{{ monitoresJSON | tojson | safe}}');
        let monitoresActuales = JSON.parse('{{ monitoresActuales | tojson | safe}}');

        let numEstudiantes = 1;

        createAutoComplete("login", "login");

        function createAutoComplete(id, tipo){
            new autoComplete({
                data: {                              // Data src [Array, Function, Async] | (REQUIRED)
                src: monitores,
                key: [tipo],
                cache: true
                },
                sort: (a, b) => {                    // Sort rendered results ascendingly | (Optional)
                    if (a.match < b.match) return -1;
                    if (a.match > b.match) return 1;
                    return 0;
                },
                placeHolder: tipo,     // Place Holder text                 | (Optional)
                selector: "#" + id,           // Input field selector              | (Optional)
                threshold: 0,                        // Min. Chars length to start Engine | (Optional)
                debounce: 300,                       // Post duration for engine to start | (Optional)
                searchEngine: "strict",              // Search Engine type/mode           | (Optional)
                resultsList: {                       // Rendered results list object      | (Optional)
                    render: true,
                    container: source => {
                        source.setAttribute("id", tipo + "_list"+id);
                    },
                    destination: document.querySelector("#"+id),
                    position: "afterend",
                    element: "ul"
                },
                maxResults: 5,                         // Max. number of rendered results | (Optional)
                highlight: true,                       // Highlight matching results      | (Optional)
                resultItem: {                          // Rendered result item            | (Optional)
                    content: (data, source) => {
                        source.innerHTML = data.match;
                    },
                    element: "li"
                },
                noResults: () => {                     // Action script on noResults      | (Optional)
                    const result = document.createElement("li");
                    result.setAttribute("class", "no_result");
                    result.setAttribute("tabindex", "1");
                    result.innerHTML = "Sin resultados";
                    result.setAttribute("onclick","mostrarBotonAgregarMonitor()")
                    document.querySelector("#"+ tipo + "_list"+id).appendChild(result);
                },
                onSelection: feedback => {             // Action script onSelection event | (Optional)
                    estudianteSeleccionado(feedback.selection.value, id)
                }
            });
        }

        function estudianteSeleccionado(estudiante, idString) {
            document.getElementById("login").value = estudiante.login;
            document.getElementById("nombres").innerHTML = estudiante.nombres;
            document.getElementById("nombres").classList.remove("notFound");
            document.getElementById("nombres").classList.add("found");
            document.getElementById("apellidos").innerHTML = estudiante.apellidos;
            document.getElementById("apellidos").classList.remove("notFound");
            document.getElementById("apellidos").classList.add("found");
        }

        function verificarMonitorSeleccionado(e){
            e.preventDefault()
            let campoVacio = false;
            let monitorNuevo = true;
            let loginMonitor = document.getElementById("login").value;
                for(let j = 0; j< monitoresActuales.length && monitorNuevo; j++){
                    let monitorActual = monitoresActuales[j];
                    if (monitorActual === loginMonitor){
                        monitorNuevo = false;
                    }
                }
                 if (loginMonitor === ""){
                    campoVacio = true;
                }

            if(!campoVacio && monitorNuevo){
                actionFormbuttonAnadirMonitor.action = "/usuarios/" + semestre_id.innerHTML + "/"+ curso_id.innerHTML+ "/agregarAsistente" + loginMonitor;
                buttonAnadirMonitor.click();
            } else if (campoVacio){
                alert("No se ha seleccionado ningun asistente graduado")
            } else if (!monitorNuevo){
                alert("El asistente graduado seleccionado ya está asignado para este curso y este semestre")
            }   
        }

        function mostrarBotonAgregarMonitor(){
            botonCrearMonitor.style.display = "block";
        }
    </script>
{% endblock content %}

Herramienta/templates/usuarios/crear_monitor.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-2">Crear {{ legend }}</legend>
                        <p>Por favor ingresar el usuario del correo Uniandes</p>
                        <div class="form-group">
                            {{ form.login.label(class="form-control-label") }}

                            {% if form.login.errors %}
                            {{ form.login(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedbakc">
                                {% for error in form.login.errors%}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.login(class="form-control form-control-lg") }}
                            {% endif %}

                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/usuarios/crear_usuario.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-2">Crear usuario</legend>
                        <p>Por favor ingresar el usuario del correo Uniandes y el tipo de usuario a crear</p>
                        <div class="form-group">
                            {{ form.login.label(class="form-control-label") }}

                            {% if form.login.errors %}
                            {{ form.login(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedbakc">
                                {% for error in form.login.errors%}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.login(class="form-control form-control-lg") }}
                            {% endif %}

                        </div>
                        <div class="form-group">
                            {{ form.rol.label(class="form-control-label") }}
                            {% if form.rol.errors %}
                            {{ form.rol(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedbakc">
                                {% for error in form.rol.errors%}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <br>
                            {{ form.rol(size=1, maxlength=50,class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/usuarios/cuenta.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-7">
            <h1>Mi cuenta</h1>
                <article class="media content-section">
                    <div class="media-body">
                        <div class="article-metadata">
                            <h3 class="mr-2">{{ usuario.login }}</h3>
                        </div>
                        <p> <strong>Rol:</strong> {{ rol.nombre }}</p>
                    </div>
                </article>
        </div>
        <div class="col-md-5">
            <div class="content-section">
                <h3>Acciones sobre la cuenta</h3>
                <form action="{{ url_for('usuarios.cambiar_contrasena', usuario_id=usuario.id) }}">
                    <button type="submit" class="btn btn-outline-info usuariossActionsButton">Cambiar contraseña</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/usuarios/editarNombre_usuario.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Cambiar login usuario</legend>
                        <div class="form-group">
                            {{ form.login.label(class="form-control-label") }}

                            {% if form.login.errors %}
                            {{ form.login(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedbakc">
                                {% for error in form.login.errors%}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.login(class="form-control form-control-lg") }}
                            {% endif %}

                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/usuarios/eliminar_usuario.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('usuarios.ver_usuarios', usuario_id=usuario.id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <legend class="border-bottom mb-4">Eliminar usuario</legend>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-danger")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/usuarios/usuarios.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-7">
            <h1>Lista de usuarios</h1>
            {% for usuario in usuarios.items %}
                <article class="media content-section">
                    <div class="media-body">
                        <div class="article-metadata">
                            <h3 class="mr-2">{{ usuario.login }}</h3>
                        </div>
                        {% if usuario.rol_id == 1 %}
                            <p class="pRol"> <strong>Rol:</strong> Monitor</p>
                        {% elif usuario.rol_id == 2 %}
                            <p class="pRol"> <strong>Rol:</strong> Asistente</p>
                        {% elif usuario.rol_id == 3 %}
                            <p class="pRol"> <strong>Rol:</strong> Profesor</p>
                        {% elif usuario.rol_id == 4 %}
                            <p class="pRol"> <strong>Rol:</strong> Admin</p>
                        {% endif%}
                        <form action="{{ url_for('usuarios.ver_usuario', usuario_id=usuario.id) }}">
                            <button type="submit" class="btn btn-outline-info verButton">Ver usuario</button>
                        </form>
                    </div>
                </article>
            {% endfor %}
            {% for page_num in usuarios.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if usuarios.page == page_num %}
                        <a class="btn btn-info mb-4" href="{{ url_for('usuarios.get_usuarios', page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="btn btn-outline-info mb-4" href="{{ url_for('usuarios.get_usuarios', page=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                    {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>
        <div class="col-md-5">
            {% if current_user.rol_id == 2 or current_user.rol_id == 3 or current_user.rol_id == 4%}
                <div class="content-section">
                    <h3>Acciones usuarios</h3>
                    <form action="{{ url_for('usuarios.register') }}">
                        <button type="submit" class="btn btn-outline-info usuariossActionsButton">Crear usuario</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}