Herramienta/semestres/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField, IntegerField
from wtforms.validators import DataRequired, Length, ValidationError, NumberRange
from flask_login import current_user
from Herramienta.models import Semestre, Estudiante


class CrearSemestreForm(FlaskForm):
    nombre = StringField("Nombre", validators=[
                        DataRequired(), Length(min=1, max=50)])
    submit = SubmitField("Crear semestre")

    def validate_nombre(self, nombre):
        user = Semestre.query.filter_by(nombre=nombre.data).first()
        if user:
            raise ValidationError("Semestre ya existente")

class EditarNombreSemestreForm(FlaskForm):
    nombre = StringField("Nombre", validators=[
                        DataRequired(), Length(min=1, max=50)])
    submit = SubmitField("Cambiar nombre")

    def validate_nombre(self, nombre):
        user = Semestre.query.filter_by(nombre=nombre.data).first()
        if user:
            raise ValidationError("Semestre ya existente")

class AgregarCursoASemestreForm(FlaskForm) :
    curso = SelectField("Curso a añadir", choices=[], coerce=int)
    submit = SubmitField("Agregar curso a semestre") 

class EliminarCursoASemestreForm(FlaskForm) :
    submit = SubmitField("Eliminar curso") 

class EliminarEstudianteForm(FlaskForm) :
    submit = SubmitField("Eliminar estudiante") 

class EliminarSemestreForm(FlaskForm) :
    submit = SubmitField("Eliminar semestre") 

class CargarListaEstudiantesForm(FlaskForm):
    archivo = FileField(u'Archivo de Excel', validators=[FileAllowed(['xlsx'])])
    submit = SubmitField("Cargar lista de estudiantes")

class DescargarListaEstudiantesForm(FlaskForm):
    submit = SubmitField("Descargar lista de estudiantes") 

class DescargarFormatoListaEstudiantesForm(FlaskForm):
    submit = SubmitField("Descargar formato lista de estudiantes") 

class EstudianteForm(FlaskForm):
    nombres = StringField("Nombres", validators=[DataRequired()])
    apellidos = StringField("Apellidos", validators=[DataRequired()])
    codigo = IntegerField("Código", validators=[DataRequired()])
    login = StringField("Login", validators=[DataRequired()])
    magistral = StringField("Magistral", validators=[DataRequired()])
    complementaria = StringField("Complementaria", validators=[DataRequired()])
    submit = SubmitField("Aceptar")

Herramienta/semestres/routes.py
import os
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort, current_app, send_file
from flask_login import current_user, login_required
from Herramienta.models import Usuario, Semestre, Curso, Estudiante, SemestreCursoHabilitados, Actividad, Calificacion, Grupo
from Herramienta import db, bcrypt
from Herramienta.semestres.forms import (CrearSemestreForm, EditarNombreSemestreForm,
                                         AgregarCursoASemestreForm, EliminarCursoASemestreForm, EliminarSemestreForm, CargarListaEstudiantesForm, DescargarListaEstudiantesForm, DescargarFormatoListaEstudiantesForm, EstudianteForm, EliminarEstudianteForm)
from openpyxl import load_workbook, Workbook

semestres = Blueprint("semestres", __name__)

@semestres.route("/semestres")
@login_required
def get_semestres():
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    page = request.args.get("page", 1, type=int)
    semestres = Semestre.query.order_by(
        Semestre.id.desc()).paginate(page=page, per_page=5)
    return render_template("semestres/semestres.html", title="Semestres", semestres=semestres)


@semestres.route("/crear_semestre", methods=["GET", "POST"])
@login_required
def crear_semestre():
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    form = CrearSemestreForm()
    if form.validate_on_submit():
        semestre = Semestre(nombre=form.nombre.data)
        db.session.add(semestre)
        db.session.commit()
        flash(f"Semestre creado exitosamente", "success")
        return redirect(url_for("semestres.get_semestres"))
    return render_template("semestres/crear_semestre.html", title="Crear semestre", form=form)


@semestres.route("/semestres/<int:semestre_id>", methods=["GET", "POST"])
@login_required
def ver_semestre(semestre_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    semestre = Semestre.query.get_or_404(semestre_id)
    return render_template("semestres/ver_semestre.html", title="Editar semestre", semestre=semestre)


@semestres.route("/semestres/<int:semestre_id>/editarNombre", methods=["GET", "POST"])
@login_required
def editarNombre_semestre(semestre_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    semestre = Semestre.query.get_or_404(semestre_id)
    form = EditarNombreSemestreForm()
    if form.validate_on_submit():
        semestre.nombre = form.nombre.data
        db.session.commit()
        flash(f"Semestre actualizado exitosamente", "success")
        return redirect(url_for("semestre.ver_semestre"))
    elif request.method == "GET":
        form.nombre.data = semestre.nombre
    return render_template("semestres/editar_nombre_semestre.html", title="Cambiar nombre semestre", form=form, semestre=semestre)


@semestres.route("/semestres/<int:semestre_id>/agregarCurso", methods=["GET", "POST"])
@login_required
def agregarCurso_semestre(semestre_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    semestre = Semestre.query.get_or_404(semestre_id)
    cursosActuales = semestre.cursos
    cursos = [(c.id, c.nombre)
              for c in Curso.query.all() if c not in cursosActuales]
    form = AgregarCursoASemestreForm(request.form)
    form.curso.choices = cursos
    if form.validate_on_submit():
        cursoAnadir = Curso.query.filter_by(id=form.curso.data).first()
        semestre.cursos.append(cursoAnadir)
        semestreCurso = SemestreCursoHabilitados(semestre_id=semestre_id,curso_id=cursoAnadir.id,habilitado=True)
        db.session.add(semestreCurso)
        db.session.commit()
        flash(f"Curso añadido exitosamente", "success")
        return redirect(url_for("semestres.ver_semestre", semestre_id=semestre.id))
    return render_template("semestres/anadirCurso_semestre.html", title="Anadir curso a semestre", form=form, semestre=semestre, cursos=cursos)


@semestres.route("/semestres/<int:semestre_id>/eliminarCurso/<int:curso_id>", methods=["GET", "POST"])
@login_required
def eliminarCurso_semestre(semestre_id, curso_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    semestre = Semestre.query.get_or_404(semestre_id)
    curso = Curso.query.get_or_404(curso_id)
    form = EliminarCursoASemestreForm()
    if form.validate_on_submit():
        semestre.cursos.remove(curso)
        semestreCurso = SemestreCursoHabilitados.query.filter_by(semestre_id=semestre_id, curso_id=curso_id).first()
        db.session.delete(semestreCurso)
        db.session.commit()
        flash(f"Curso eliminado exitosamente", "success")
        return redirect(url_for("semestres.ver_semestre", semestre_id=semestre.id))
    return render_template("semestres/eliminarCurso_semestre.html", title="Eliminar curso a semestre", form=form, semestre=semestre, curso=curso)


@semestres.route("/semestres/<int:semestre_id>/eliminarSemestre", methods=["GET", "POST"])
@login_required
def eliminar_semestre(semestre_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    semestre = Semestre.query.get_or_404(semestre_id)
    actividades = Actividad.query.filter_by(semestre_id=semestre.id).all()
    estudiantes = Estudiante.query.filter_by(semestre=semestre.id).all()
    form = EliminarSemestreForm()
    if form.validate_on_submit():
        for curso in semestre.cursos:
            semestre.cursos.remove(curso)
            semestreCurso = SemestreCursoHabilitados.query.filter_by(semestre_id=semestre.id, curso_id=curso.id).first()
            db.session.delete(semestreCurso)
            db.session.commit()
        for estudiante in estudiantes:
            semestre.estudiantes.remove(estudiante)
            db.session.delete(estudiante)
            db.session.commit()
        for actividad in actividades:
            grupos = Grupo.query.filter_by(actividad_id=actividad.id).all()
            for grupo in grupos:
                listaCalificaciones = Calificacion.query.filter_by(grupo_id=grupo.id).all()
                for calificacion in listaCalificaciones:
                    db.session.delete(calificacion)
                    db.session.commit()
                db.session.delete(grupo)
                db.session.commit()
            eliminarActividad(actividad.id)
            db.session.commit()
        db.session.delete(semestre)
        db.session.commit()
        flash(f"Semestre eliminado exitosamente", "success")
        return redirect(url_for("semestres.get_semestres"))
    return render_template("semestres/eliminar_semestre.html", title="Eliminar semestre", form=form, semestre=semestre)

@semestres.route("/semestres/<int:semestre_id>/<int:curso_id>/verLista", methods=["GET", "POST"])
@login_required
def verLista_semestre(semestre_id,curso_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    semestre = Semestre.query.get_or_404(semestre_id)
    return render_template("semestres/verLista_semestre.html", title="Ver lista estudiantes", semestre=semestre, curso_id=curso_id)

@semestres.route("/semestres/<int:semestre_id>/<int:curso_id>/cargarLista", methods=["GET", "POST"])
@login_required
def cargarListaEstudiantes_semestre(semestre_id,curso_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    semestre = Semestre.query.get_or_404(semestre_id)
    form = CargarListaEstudiantesForm()
    if form.validate_on_submit():
        if form.archivo.data:
            if request.method == 'POST':
                f = request.files['archivo']
                f.save(os.path.join(current_app.root_path, 'static/files', "ListaEstudiantes.xlsx"))
                analisis = analizarArchivoListaEstudiantes(semestre)
                if analisis:
                    flash(f"Lista de estudiantes importada exitosamente", "success")
                    return redirect(url_for("semestres.verLista_semestre", curso_id=curso_id, semestre_id=semestre_id))
                else:
                    flash(f"El archivo no pudo ser procesado porque no cumple con la estructura.", "danger")
                    return redirect(url_for("semestre.verLista_semestre", curso_id=curso_id, semestre_id=semestre_id))
    return render_template("semestres/cargarLista_semestre.html", title="Añadir estudiante", semestre=semestre, curso_id=curso_id, form=form)

def analizarArchivoListaEstudiantes(semestre):
    exito = True
    archivoExcel = load_workbook(current_app.root_path + '/static/files/ListaEstudiantes.xlsx')
    hoja = archivoExcel.active
    fila = 2
    final = False
    while not final:

Herramienta/templates/semestres/anadirCurso_semestre.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('semestres.ver_semestre', semestre_id=semestre.id) }}">
                    <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Añadir curso a semestre</legend>
                        <div class="form-group">
                            {{ form.curso.label(class="form-control-label") }}
                            {% if form.curso.errors %}
                            {{ form.curso(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedbakc">
                                {% for error in form.curso.errors%}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <br>
                            {{ form.curso(size=1, maxlength=50,class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/semestres/cargarLista_semestre.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('actividades.crear_actividad', curso_id=curso_id, semestre_id=semestre.id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Cargar lista de estudiantes - {{ semestre.nombre }}</legend>
                        <div class="form-group">
                            {{ form.archivo.label() }}
                            {{ form.archivo(class="form-control-file") }}
                            {% if form.archivo.errors %}
                                {% for error in form.archivo.errors %}
                                    <span class="text-danger">{{ error }}</span></br>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/semestres/crear_semestre.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Crear semestre</legend>
                        <div class="form-group">
                            {{ form.nombre.label(class="form-control-label") }}

                            {% if form.nombre.errors %}
                            {{ form.nombre(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedbakc">
                                {% for error in form.nombre.errors%}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.nombre(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.curso_id.label(class="form-control-label") }}
                            {% if form.curso_id.errors %}
                            {{ form.curso_id(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedbakc">
                                {% for error in form.curso_id.errors%}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <br>
                            {{ form.curso_id(size=1, maxlength=50,class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/semestres/descargarFormatoListaEstudiantes.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('semestres.verLista_semestre', curso_id=curso_id, semestre_id=semestre_id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <legend class="border-bottom mb-4">Descargar formato lista de estudiantes</legend>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/semestres/descargarListaEstudiantes.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('semestres.verLista_semestre', curso_id=curso_id, semestre_id=semestre_id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <legend class="border-bottom mb-4">Descargar lista de estudiantes</legend>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/semestres/eliminarCurso_semestre.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('semestres.ver_semestre', semestre_id=semestre.id) }}">
                    <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
                <div class="content-section">
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Eliminar curso a semestre</legend>
                            <h5>¿Desea eliminar el curso {{ curso.nombre}} del semestre {{ semestre.nombre }}?</h5>
                        </fieldset>
                        <div class="form-group">
                            {{ form.submit(class="btn btn-outline-info")}}
                        </div>
                    </form>
                </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/semestres/semestres.html
{% extends "layout.html" %}

{% block content %}
<div class="row">
    <div class="col-md-7">
        <h1>Lista de semestres</h1>
        {% if not semestres.items %}
            <h4>No hay semestres</h4>
        {% else %}
            {% for semestre in semestres.items %}
            <article class="media content-section">
                <div class="media-body">
                    <div class="article-metadata">
                        <h2><a class="mr-2">{{ semestre.nombre }}</a></h2>
                    </div>
                    <form action="{{ url_for('semestres.ver_semestre', semestre_id=semestre.id) }}">
                        <button type="submit" class="btn btn-outline-info verButton">Ver semestre</button>
                    </form>
                </div>
            </article>
            {% endfor %}
        {% endif %}
        {% for page_num in semestres.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if semestres.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('semestres.get_semestres', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('semestres.get_semestres', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    </div>
    <div class="col-md-5">
        {% if current_user.rol_id == 2 or current_user.rol_id == 3 or current_user.rol_id == 4%}
        <div class="content-section">
            <h3>Acciones semestres</h3>
            <div>
                <form action="{{ url_for('semestres.crear_semestre') }}">
                    <button type="submit" class="btn btn-outline-info cursosActionsButton">Crear semestre</button>
                </form>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

Herramienta/templates/semestres/verLista_semestre.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <form action="{{ url_for('cursos.ver_curso', curso_id=curso_id) }}">
                    <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <article class="media content-section">
                <div class="media-body">
                    <div class="article-metadata">
                        <h4 class="mr-2">{{ semestre.nombre }}</h4>
                    </div>
                    <h4>Lista de estudiantes</h4>
                    {% if not semestre.estudiantes %}
                        <form action="{{ url_for('semestres.cargarListaEstudiantes_semestre', curso_id=curso_id, semestre_id=semestre.id) }}">
                            <button type="submit" class="btn btn-outline-info semestreActions">Cargar lista de estudiantes</button>
                        </form>
                        <form action="{{ url_for('semestres.descargarFormatoListaEstudiantes_semestre', curso_id=curso_id, semestre_id=semestre.id) }}">
                            <button type="submit" class="btn btn-outline-info semestreActions">Descargar formato lista de estudiantes</button>
                        </form>
                        <br>
                        <p>No hay estudiantes asignados a este semestre</p>
                    {% else %}
                    <form action="{{ url_for('semestres.crearEstudiante_semestre', curso_id=curso_id, semestre_id=semestre.id) }}">
                        <button type="submit" class="btn btn-outline-info semestreActions">Crear estudiante</button>
                    </form>
                    <table id="listaEstudiantes" class="hover" style="width:100%">
                        <thead>
                            <tr>
                                <th>Login</th>
                                <th>Código</th>
                                <th>Apellidos</th>
                                <th>Nombres</th>
                                    <th>
                                        <img class="habilitarButton" src="/static/icons/edit.png" alt="edit image">
                                    </th>
                                <th>
                                    <img class="habilitarButton" src="/static/icons/trash.png" alt="edit image">
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for estudiante in semestre.estudiantes %}
                            <tr>
                                <td>{{ estudiante.login }}</td>
                                <td>{{ estudiante.codigo }}</td>
                                <td>{{ estudiante.apellido }}</td>
                                <td>{{ estudiante.nombre }}</td>
                                <td>
                                    <form action="{{ url_for('semestres.editarEstudiante_semestre', curso_id=curso_id, semestre_id=semestre.id, estudiante_id=estudiante.id) }}">
                                        <button type="submit" class="checkButton"><img src="/static/icons/edit.png" class="habilitarButton" alt="check image"></button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{ url_for('semestres.eliminar_estudiante', curso_id=curso_id, semestre_id=semestre.id, estudiante_id=estudiante.id) }}">
                                        <button type="submit" class="checkButton"><img src="/static/icons/trash.png" class="habilitarButton" alt="check image"></button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Login</th>
                                <th>Código</th>
                                <th>Apellidos</th>
                                <th>Nombres</th>
                                    <th>
                                        <img class="habilitarButton" src="/static/icons/edit.png" alt="edit image">
                                    </th>
                                <th>
                                    <img class="habilitarButton" src="/static/icons/trash.png" alt="edit image">
                                </th>
                            </tr>
                        </tfoot>
                    </table>
                    <br>
                    <form action="{{ url_for('semestres.descargarListaEstudiantes_semestre', curso_id=curso_id, semestre_id=semestre.id) }}">
                        <button type="submit" class="btn btn-outline-info semestreActions">Descargar lista de estudiantes</button>
                    </form>
                    {% endif %}
                </div>
            </article>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $('#listaEstudiantes').DataTable({
                "language" : {
                    "url" : "//cdn.datatables.net/plug-ins/1.10.20/i18n/Spanish.json"
                }
            });
        } );
    </script>
{% endblock content %}

Herramienta/templates/semestres/ver_semestre.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <form action="{{ url_for('semestres.get_semestres')}}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <br>
                <article class="media content-section">
                    <div class="media-body">
                        <div class="article-metadata">
                            <h3 class="mr-2">{{ semestre.nombre }} - Acciones sobre el semestre</h3>
                        </div>
                        <form action="{{ url_for('semestres.editarNombre_semestre', semestre_id=semestre.id) }}">
                            <button type="submit" class="btn btn-outline-info semestreActions">Cambiar nombre semestre</button>
                        </form>
                        <form action="{{ url_for('semestres.eliminar_semestre', semestre_id=semestre.id) }}">
                            <button type="submit" class="btn btn-outline-danger semestreActions">Eliminar semestre</button>
                        </form>
                    </div>
                </article>

                <article class="media content-section">
                    <div class="media-body">
                            <div class="article-metadata">
                                <h3 class="mr-2">{{ semestre.nombre }} - Acciones sobre los cursos del semestre</h3>
                            </div>
                            <form action="{{ url_for('semestres.agregarCurso_semestre', semestre_id=semestre.id) }}">
                                <button type="submit" class="btn btn-outline-info semestreActions">Agregar curso a semestre</button>
                            </form>
                            <h4>Lista de cursos:</h4>
                            <ul style="list-style-type:disc;" class="cursosListInSemestre">
                                {% if not semestre.cursos %}
                                    <li>Ninguno</li>
                                {% else %}
                                    {% for curso in semestre.cursos %}
                                        <li>
                                            <div class="cursoTextButtonLayout">
                                                {{ curso.nombre }}
                                                <form action="{{ url_for('semestres.eliminarCurso_semestre', semestre_id=semestre.id,  curso_id=curso.id) }}">
                                                    <button type="submit" class="btn btn-outline-danger eliminarCursoSemestre">Eliminar curso</button>
                                                </form>
                                            </div>
                                        </li>
                                    {% endfor %}
                                {% endif %}
                            </ul>
                    </div>
                </article>
        </div>
    </div>
{% endblock content %}