Herramienta/actividades/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField, IntegerField, FieldList, FormField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from Herramienta.models import Curso

class CrearActividadArchivoForm(FlaskForm):
    archivo = FileField(u'Archivo de Excel', validators=[FileAllowed(['xlsx'])])
    submit = SubmitField("Crear actividad")

class EliminarActividad(FlaskForm):
    submit = SubmitField("Eliminar actividad")

class EliminarGrupo(FlaskForm): 
    submit = SubmitField("Eliminar grupo")

class DescargarActividad(FlaskForm):
    submit = SubmitField("Descargar actividad") 

class CrearPunto(FlaskForm):
    nombre = StringField("Nombre del punto", validators=[
                        DataRequired(), Length(min=1, max=100)])
    submit = SubmitField("Crear punto")

class CambiarEstadoActividad(FlaskForm):
    submit = SubmitField("Cambiar estado")

class EnviarReportes(FlaskForm):
    submit = SubmitField("Enviar reportes")

class GenerarReporte(FlaskForm):
    submit = SubmitField("Generar informe")

class IntegranteForm(FlaskForm):
    codigo = SelectField("Código", choices=[], coerce=int)

class EscogerGrupoParaCalificar(FlaskForm):
    grupo = SelectField("Grupo", choices=[], coerce=int)
    submit = SubmitField("Seleccionar grupo para calificar")

class DescargarFormatoActividadForm(FlaskForm):
    submit = SubmitField("Descargar formato actividad") 

Herramienta/actividades/routes.py
import os
import statistics 
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort, current_app, send_file
from flask_wtf import FlaskForm
from wtforms import FieldList, FormField, SubmitField
from flask_login import current_user, login_required
from Herramienta.models import Usuario, Curso, Semestre, Actividad, Punto, Inciso, Criterio, Subcriterio, Variacion, Grupo, Estudiante, Calificacion, ListaUsuariosSemestreCurso
from Herramienta import db, bcrypt
from Herramienta.actividades.forms import CrearActividadArchivoForm, EliminarActividad, DescargarActividad, CrearPunto, CambiarEstadoActividad, EnviarReportes, IntegranteForm, EscogerGrupoParaCalificar, EliminarGrupo, DescargarFormatoActividadForm, GenerarReporte
from openpyxl import load_workbook, Workbook
from Herramienta.actividades.utils import send_reports, create_pdf

actividades = Blueprint("actividades", __name__)

@actividades.route("/actividades/<int:curso_id>/<int:actividad_id>", methods=["GET", "POST"])
@login_required
def ver_actividad(actividad_id,curso_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    actividad = Actividad.query.get_or_404(actividad_id)
    return render_template("actividades/ver_actividad.html", title="Ver actividad", actividad=actividad, curso_id=curso_id)

@actividades.route("/actividades/<int:curso_id>/<int:actividad_id>/elegirGrupoCalificar", methods=["GET", "POST"])
@login_required
def elegir_grupo_calificar_actividad(actividad_id,curso_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    actividad = Actividad.query.get_or_404(actividad_id)
    grupos = [(g.id, g.estudiantes) for g in Grupo.query.filter_by(actividad_id=actividad.id, calificaciones=None).all()]
    form = EscogerGrupoParaCalificar(request.form)
    form.grupo.choices = grupos
    if form.validate_on_submit():
        return redirect(url_for("actividades.calificar_actividad", curso_id=curso_id, actividad_id=actividad_id, grupo_id=form.grupo.data))
    return render_template("actividades/elegir_grupo_calificar.html", title="Elegir grupo para calificar actividad", actividad=actividad, curso_id=curso_id,form=form, grupos=grupos)

@actividades.route("/actividades/<int:curso_id>/<int:actividad_id>/calificar/<int:grupo_id>", methods=["GET", "POST"])
@login_required
def calificar_actividad(actividad_id,curso_id,grupo_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        habilitado = ListaUsuariosSemestreCurso.query.filter_by(usuario_id=user_id, curso_id=curso_id).first()
        if not habilitado:
            abort(403)
    actividad = Actividad.query.get_or_404(actividad_id)
    grupo = Grupo.query.get_or_404(grupo_id)
    puntaje = 0
    numSubcriterios = 0
    puntos = []
    calificacionesExistentes = []
    for punto in actividad.puntos:
        incisos = []
        for inciso in punto.incisos:
            criterios = []
            for criterio in inciso.criterios:
                subcriterios = []
                for subcriterio in criterio.subcriterios:
                    variaciones = []
                    for variacion in subcriterio.variaciones:
                        calificacionExistente = Calificacion.query.filter_by(grupo_id=grupo_id, variacion_id=variacion.id).first()
                        if calificacionExistente is not None:
                            calificacionesExistentes.append(str(variacion.id) + ":" + str(subcriterio.id))
                        variacionJSON = {
                            "id" : variacion.id,
                            "puntaje" : variacion.puntaje,
                            "esOtro" : variacion.esOtro
                        }
                        variaciones.append(variacionJSON)
                    puntaje = puntaje + subcriterio.maximoPuntaje
                    if subcriterio.maximoPuntaje > 0:
                        numSubcriterios = numSubcriterios + 1
                    subcriterioJSON = {
                        "id" : subcriterio.id,
                        "variaciones" : variaciones
                    }
                    subcriterios.append(subcriterioJSON)
                criterioJSON = {
                    "id" : criterio.id,
                    "subcriterios" : subcriterios
                }
                criterios.append(criterioJSON)
            incisoJSON = {
                "id" : inciso.id,
                "criterios" : criterios
            }
            incisos.append(incisoJSON)
        puntoJSON = {
            "id" : punto.id,
            "incisos" : incisos
        }
        puntos.append(puntoJSON)
    actividadToJson = {
        "id" : actividad.id,
        "puntos" : puntos,
        "puntaje" : puntaje,
        "numSubcriterios" : numSubcriterios,
        "calificacionesExistentes" : calificacionesExistentes
    }
    return render_template("actividades/calificar_actividad.html", title="Calificar actividad", actividad=actividad, curso_id=curso_id, actividadJSON = actividadToJson, grupo=grupo)

@actividades.route("/actividades/<int:curso_id>/<int:actividad_id>/<int:semestre_id>/eliminar", methods=["GET", "POST"])
@login_required
def eliminar_actividad(actividad_id, curso_id,semestre_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    actividad = Actividad.query.get_or_404(actividad_id)
    grupos = Grupo.query.filter_by(actividad_id=actividad.id).all()
    if user.rol_id == 1:
        abort(403)
    form = EliminarActividad()
    if form.validate_on_submit():
        for grupo in grupos:
            listaCalificaciones = Calificacion.query.filter_by(grupo_id=grupo.id).all()
            for calificacion in listaCalificaciones:
                db.session.delete(calificacion)
                db.session.commit()
            db.session.delete(grupo)
            db.session.commit()
        eliminarActividad(actividad_id)
        flash(f"Actividad eliminada exitosamente", "success")
        return redirect(url_for("actividades.verActividades_semestre", curso_id=curso_id, semestre_id=semestre_id))
    return render_template("actividades/eliminar_actividad.html", title="Eliminar actividad", curso_id=curso_id, actividad_id=actividad_id, semestre_id=semestre_id,form=form)

@actividades.route("/actividades/<int:curso_id>/<int:actividad_id>/<int:semestre_id>/cambiarEstado", methods=["GET", "POST"])
@login_required
def cambiarEstado_actividad(actividad_id,curso_id,semestre_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    actividad = Actividad.query.get_or_404(actividad_id)
    actividad.habilitada  = not actividad.habilitada
    db.session.commit()
    return redirect(url_for("actividades.verActividades_semestre", curso_id=curso_id, semestre_id=semestre_id))

@actividades.route("/actividades/<int:curso_id>/<int:semestre_id>/crearActividad")
@login_required
def crear_actividad(curso_id, semestre_id):
    return render_template("actividades/crear_actividad.html", title="Crear actividad", curso_id=curso_id, semestre_id=semestre_id)

@actividades.route("/actividades/<int:curso_id>/<int:semestre_id>/crearActividadArchivo", methods=["GET", "POST"])
@login_required
def crear_actividadArchivo(curso_id, semestre_id):
    if not current_user.activado:
        return redirect(url_for("usuarios.activar_usuario"))
    user_id = current_user.get_id()
    user = Usuario.query.filter_by(id=user_id).first()
    if user.rol_id == 1:
        abort(403)
    form = CrearActividadArchivoForm()
    if form.validate_on_submit():
        if form.archivo.data:
            if request.method == 'POST':
                f = request.files['archivo']
                f.save(os.path.join(current_app.root_path, 'static/files', "Actividad.xlsx"))
                analisis = analizarArchivo(curso_id,semestre_id)
                if analisis is None:
                    flash(f"Actividad creada exitosamente", "success")
                elif analisis == "nombre":
                    flash(f"El archivo no pudo ser procesado porque ya existe una actividad con ese nombre.", "danger")
                elif analisis == "porcentaje":
                    flash(f"El archivo no pudo ser procesado porque el porcentaje no es un numero.", "danger")
                elif analisis == "porcentajeMayorACero":
                    flash("El archivo no pudo ser procesado porque el valor de porcentaje es mayor a 1", "danger")
                elif analisis == "integrantes":
                    flash("El archivo no pudo ser procesado porque el número de integrantes es menor o igual a 0.", "danger")
                elif analisis.startswith("formato"):
                    lugar = analisis.split(":")
                    flash("El archivo no pudo ser procesado porque hay un error en la fila " + lugar[1] + " columna " +lugar[2], "danger")
                elif analisis.startswith("2formato"):
                    lugar = analisis.split(":")
                    flash("El archivo no pudo ser procesado porque hay un error en la fila " + lugar[1], "danger")
                return redirect(url_for("actividades.verActividades_semestre", curso_id=curso_id, semestre_id=semestre_id))
    return render_template("actividades/crear_actividadArchivo.html", title="Crear actividad desde archivo", curso_id=curso_id, form=form, semestre_id=semestre_id)


def analizarArchivo(curso_id, semestre_id):
    tipoError = None

Herramienta/templates/actividades/crear_actividad.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('actividades.verActividades_semestre', curso_id=curso_id, semestre_id=semestre_id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <legend class="border-bottom mb-4">Crear actividad</legend>
                <form action="{{ url_for('actividades.crear_actividadArchivo', curso_id=curso_id, semestre_id=semestre_id) }}">
                    <button type="submit" class="btn btn-outline-info semestreActions">Crear desde archivo xlsx</button>
                </form>
                <form action="{{ url_for('actividades.crear_actividad', curso_id=curso_id, semestre_id=semestre_id) }}">
                    <button type="submit" class="btn btn-outline-info semestreActions">Crear desde vista web</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/actividades/crear_actividadArchivo.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('actividades.crear_actividad', curso_id=curso_id,semestre_id=semestre_id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Crear actividad desde Archivo</legend>
                        <div class="form-group">
                            {{ form.archivo.label() }}
                            {{ form.archivo(class="form-control-file") }}
                            {% if form.archivo.errors %}
                                {% for error in form.archivo.errors %}
                                    <span class="text-danger">{{ error }}</span></br>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/actividades/descargarFormatoActividades.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('actividades.verActividades_semestre', curso_id=curso_id, semestre_id=semestre_id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <legend class="border-bottom mb-4">Descargar formato actividades</legend>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/actividades/descargar_actividad.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('actividades.ver_actividad', curso_id=curso_id, actividad_id=actividad_id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <legend class="border-bottom mb-4">Descargar actividad</legend>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/actividades/descargar_notas.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('actividades.ver_grupos_actividad', curso_id=curso_id, actividad_id=actividad_id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <legend class="border-bottom mb-4">Descargar notas</legend>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/actividades/elegir_grupo_calificar.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-7">
            <form action="{{ url_for('cursos.ver_curso', curso_id=curso_id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            {% if not grupos %}
                <p>No hay grupos disponibles para calificar</p>
            {% else %}
                <div class="content-section">
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-2">Elegir grupo para calificar</legend>
                            <div class="form-group">
                                {{ form.grupo.label(class="form-control-label") }}
                                {% if form.grupo.errors %}
                                {{ form.grupo(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedbakc">
                                    {% for error in form.grupo.errors%}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                <br>
                                {{ form.grupo(size=1, maxlength=50,class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                        </fieldset>
                        <div class="form-group">
                            {{ form.submit(class="btn btn-outline-info")}}
                        </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

Herramienta/templates/actividades/eliminar_actividad.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('actividades.ver_actividad', curso_id=curso_id, actividad_id=actividad_id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <legend class="border-bottom mb-2">Eliminar actividad</legend>
                    <p>¿Desea eliminar de forma permante la actividad? Esta acción no puede deshacerse.</p>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-danger")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/actividades/eliminar_grupo.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('actividades.ver_grupos_actividad', curso_id=curso.id, actividad_id=actividad.id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <legend class="border-bottom mb-2">Eliminar grupo</legend>
                    <p>¿Desea eliminar de forma permante el grupo? Esta acción no puede deshacerse.</p>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-danger")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/actividades/enviarReportes.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
            <form action="{{ url_for('actividades.ver_actividad', curso_id=curso_id, actividad_id=actividad_id) }}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <legend class="border-bottom mb-4">Enviar informes</legend>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Herramienta/templates/actividades/ver_actividades_semestre.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <form action="{{ url_for('cursos.ver_curso', curso_id=curso.id)}}">
                <input type="image" class="BackButton" src="https://image.flaticon.com/icons/svg/271/271218.svg" />
            </form>
            <br>
            <article class="media content-section">
                <div class="media-body">
                    <div class="article-metadata">
                        <h3 class="mr-2">Actividades del semestre {{ semestre.nombre}} del curso {{ curso.nombre }} </h3>
                    </div>
                    {% if current_user.rol_id != 1 %}
                        <form action="{{ url_for('actividades.crear_actividad', curso_id=curso.id, semestre_id=semestre.id) }}">
                            <button type="submit" class="btn btn-outline-info semestreActions">Crear actividad</button>
                        </form>
                        <form action="{{ url_for('actividades.descargarFormatoActividad', curso_id=curso.id, semestre_id=semestre.id) }}">
                            <button type="submit" class="btn btn-outline-info semestreActions">Descargar formato actividad</button>
                        </form>
                    {% endif %}
                    {% if not actividades %}
                        No hay actividades asignadas a este curso en este semestre
                    {% else %}
                        <table id="listaEstudiantes" class="hover" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Núm. Grupos</th>
                                    <th>Núm. Máx. Integrantes</th>
                                    <th>Núm. Est. Calificados</th>
                                    <th>Promedio</th>
                                    <th>Desv. Est.</th>
                                    {% if current_user.rol_id != 1 %}
                                        <th>Estado</th>
                                        <th><img class="habilitarButton" src="/static/icons/tick.png" alt="check image"></th>
                                        <th><img class="habilitarButton" src="/static/icons/x.png" alt="check image"></th>
                                        <th><img class="habilitarButton" src="/static/icons/edit.png" alt="check image"></th>
                                        <th><img class="habilitarButton" src="/static/icons/trash.png" alt="check image"></th>
                                    {% endif %}
                                    <th>Calificar</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for actividad in actividades %}
                                <tr>
                                    <td>{{ actividad.nombre }}</td>
                                    <td>{{ actividad.grupos|length}}</td>
                                    <td>{{ actividad.numeroIntegrantes }}</td>
                                    <td>{{ actividad.numEstCalificados }}</td>
                                    <td>{{ '%0.2f'| format(actividad.promedio|float) }}</td>
                                    <td>{{ '%0.2f'| format(actividad.desvEst|float) }}</td>
                                    {% if current_user.rol_id != 1 %}
                                        {% if actividad.habilitada %}
                                            <td class="finalizado">Habilitada</td>
                                            <td>
                                                <img src="/static/icons/tick-disabled.png" class="habilitarButton" alt="check image">
                                            </td>
                                            <td>
                                                <form action="{{ url_for('actividades.cambiarEstado_actividad', semestre_id=semestre.id,  curso_id=curso.id, actividad_id=actividad.id) }}">
                                                    <button type="submit" class="checkButton"><img src="/static/icons/x.png" class="habilitarButton" alt="check image"></button>
                                                </form>
                                            </td>
                                        {% else %}
                                            <td class="noFinalizado">Deshabilitada</td>
                                            <td>
                                                <form action="{{ url_for('actividades.cambiarEstado_actividad', semestre_id=semestre.id,  curso_id=curso.id, actividad_id=actividad.id) }}">
                                                    <button type="submit" class="checkButton"><img src="/static/icons/tick.png" class="habilitarButton" alt="check image"></button>
                                                </form>
                                            </td>
                                            <td>
                                                <img src="/static/icons/x-disabled.png" class="habilitarButton" alt="check image">
                                            </td>
                                        {% endif %}
                                        <td>
                                            <form action="{{ url_for('actividades.ver_actividad', actividad_id=actividad.id, curso_id=curso.id) }}">
                                                <button type="submit" class="checkButton"><img class="habilitarButton" src="/static/icons/edit.png" alt="check image"></button>
                                            </form>
                                        </td>
                                        <td>
                                            <form action="{{ url_for('actividades.eliminar_actividad', semestre_id=semestre.id,  curso_id=curso.id, actividad_id=actividad.id) }}">
                                                <button type="submit" class="checkButton"><img src="/static/icons/trash.png" class="habilitarButton" alt="check image"></button>
                                            </form>
                                        </td>
                                    {% endif %}
                                    <td>
                                        <form action="{{ url_for('actividades.ver_grupos_actividad', actividad_id=actividad.id, curso_id=curso.id) }}">
                                            <button type="submit" class="btn btn-outline-info eliminarCursoSemestre">Calificar</button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Núm. Grupos</th>
                                    <th>Núm. Máx. Integrantes</th>
                                    <th>Núm. Est. Calificados</th>
                                    <th>Promedio</th>
                                    <th>Desv. Est.</th>
                                    {% if current_user.rol_id != 1 %}
                                        <th>Estado</th>
                                        <th><img class="habilitarButton" src="/static/icons/tick.png" alt="check image"></th>
                                        <th><img class="habilitarButton" src="/static/icons/x.png" alt="check image"></th>
                                        <th><img class="habilitarButton" src="/static/icons/edit.png" alt="check image"></th>
                                        <th><img class="habilitarButton" src="/static/icons/trash.png" alt="check image"></th>
                                    {% endif %}
                                    <th>Calificar</th>
                                </tr>
                            </tfoot>
                        </table>
                    {% endif %}
                </div>
            </article>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('#listaEstudiantes').DataTable({
                "language" : {
                    "url" : "//cdn.datatables.net/plug-ins/1.10.20/i18n/Spanish.json"
                }
            });
        } );
    </script>
{% endblock content %}